// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASkpg3qT0DEjiasGUkJTysHT8vZ4m3Rd8',
    appId: '1:361246833717:web:f7e03820dbe738f82b457c',
    messagingSenderId: '361246833717',
    projectId: 'fir-5097b',
    authDomain: 'fir-5097b.firebaseapp.com',
    storageBucket: 'fir-5097b.appspot.com',
    measurementId: 'G-EHB03QCVSJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwFmvgORmz3bqPh1AqSXm8l1axcdHcVzk',
    appId: '1:361246833717:android:0ca1b96a12106d112b457c',
    messagingSenderId: '361246833717',
    projectId: 'fir-5097b',
    storageBucket: 'fir-5097b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE8ySPuhJ7wmis8EUv79De3LJ_rHtWMF0',
    appId: '1:361246833717:ios:55924fff3f47d95a2b457c',
    messagingSenderId: '361246833717',
    projectId: 'fir-5097b',
    storageBucket: 'fir-5097b.appspot.com',
    iosClientId: '361246833717-9jj7rra0cqta4k0tmopm71dr3pr44nfa.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASkpg3qT0DEjiasGUkJTysHT8vZ4m3Rd8',
    appId: '1:361246833717:web:29ad1e1e817a09072b457c',
    messagingSenderId: '361246833717',
    projectId: 'fir-5097b',
    authDomain: 'fir-5097b.firebaseapp.com',
    storageBucket: 'fir-5097b.appspot.com',
    measurementId: 'G-GMTCQ92L1K',
  );
}
